networks:
  charlymatloc.net:
    driver: bridge

services:
  # service API
  api.charlymatloc:
    build:
      context: ./build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - charlymatloc.net
    depends_on:
      - charlymatloc.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # service DB
  charlymatloc.db:
    image: 'postgres:latest'
    env_file: ./charlymatloc.env
    ports:
      - '5432:5432'
    networks:
      - charlymatloc.net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  # administration de la base SQL
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - charlymatloc.net

# déclaration du volume persistant
volumes:
  pgdata:
